# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtDescricao', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtNome', models.CharField(max_length=100)),
                ('txtEmail', models.CharField(max_length=100)),
                ('txtTelefone', models.CharField(max_length=11)),
                ('txtCPF', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Teleconsultor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtNome', models.CharField(max_length=100)),
                ('txtEmail', models.CharField(max_length=100)),
                ('txtCRM', models.CharField(max_length=20)),
                ('dtFormatura', models.CharField(max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleconsultoria.Solicitante'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='teleconsultor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleconsultoria.Teleconsultor'),
        ),
    ]
