# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='solicitante',
            field=models.ForeignKey(null='false', on_delete=django.db.models.deletion.CASCADE, to='teleconsultoria.Solicitante'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='teleconsultor',
            field=models.ForeignKey(null='false', on_delete=django.db.models.deletion.CASCADE, to='teleconsultoria.Teleconsultor'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='txtDescricao',
            field=models.CharField(max_length=500, null='false'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='txtCPF',
            field=models.CharField(max_length=11, null='false'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='txtEmail',
            field=models.CharField(max_length=100, null='false'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='txtNome',
            field=models.CharField(max_length=100, null='false'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='txtTelefone',
            field=models.CharField(max_length=11, null='false'),
        ),
        migrations.AlterField(
            model_name='teleconsultor',
            name='dtFormatura',
            field=models.DateTimeField(default=django.utils.timezone.now, null='false'),
        ),
        migrations.AlterField(
            model_name='teleconsultor',
            name='txtCRM',
            field=models.CharField(max_length=20, null='false'),
        ),
        migrations.AlterField(
            model_name='teleconsultor',
            name='txtEmail',
            field=models.CharField(max_length=100, null='false'),
        ),
        migrations.AlterField(
            model_name='teleconsultor',
            name='txtNome',
            field=models.CharField(max_length=100, null='false'),
        ),
    ]
